server:
  port: 8082

spring:
  datasource:
    ### PostgreSQL configuration ###
    url: jdbc:postgresql://localhost:5432/license_manager
    username: mdzahidraza
    password: zahid
    platform: postgresql
    initialize: true
    continue-on-error: false
    ### MySQL configuration ###
#    url: jdbc:mysql://localhost:3306/license_manager?createDatabaseIfNotExist=true
#    username: root
#    password: zahid
#    platform: mysql
#    initialize: true
#    continue-on-error: true

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

security:
  filter-order: 0
  oauth2:
    resource:
      id: TEST_RESOURCE
      filter-order: 3
#
#
#
##server { # simple reverse-proxy
##  listen              443 ssl;
##  server_name         jaza-soft.com  www.jaza-soft.com;
##  ssl_certificate     jaza-soft.com.crt;
##  ssl_certificate_key jaza-soft.com.key;
##  ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
##  ssl_ciphers         HIGH:!aNULL:!MD5;
##  #listen       80;
##  #server_name  jaza-soft.com;
##  access_log   logs/jaza-soft.access.log  main;
##
##  # pass requests for dynamic content to rails/turbogears/zope, et al
##  location / {
##    proxy_pass      http://139.59.58.107:8080/;
##  }
##}
#
#http only:
#
#server {
#    listen 80;
#    server_name         jaza-soft.com www.jaza-soft.com;
#
#    location / {
#      proxy_pass      http://139.59.58.107:8080/;
#    }
#
#}
#
#
#server {
#    listen       80;
#    server_name  jaza-soft.com;
#    rewrite ^ https://$http_host$request_uri? permanent;    # force redirect http to https
#    server_tokens off;
#}
#
#server {
#    listen 443 ssl;
#    server_name         jaza-soft.com;
#    ssl_certificate     jaza-soft.com.crt;        # path to your cacert.pem
#    ssl_certificate_key jaza-soft.com.key;    # path to your privkey.pem
#
#    server_tokens off;
#
#    fastcgi_param   HTTPS               on;
#    fastcgi_param   HTTP_SCHEME         https;
#
#    location / {
#      proxy_pass      http://139.59.58.107:8080/;
#    }
#}
#
#CBF2920AD08268713121356745322757.www.jaza-soft.com
#
