server:
  port: 8082

spring:
  datasource:
    ### PostgreSQL configuration ###
#    url: jdbc:postgresql://localhost:5432/license_manager
#    username: mdzahidraza
#    password: zahid
#    platform: postgresql
#    initialize: true
#    continue-on-error: true
    ### MySQL configuration ###
    url: jdbc:mysql://localhost:3306/license_manager?createDatabaseIfNotExist=true
    username: root
    password: zahid
    platform: mysql
    initialize: true
    continue-on-error: true

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

security:
  filter-order: 0
  oauth2:
    resource:
      id: TEST_RESOURCE
      filter-order: 3